version: "3"

services:
  mysql:
    image: mysql:5.6.34
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE={MYSQL_DATABASE}

  app:
    build:
      context: .
    command: bundle exec puma --config config/puma.rb
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ".:/app"
    depends_on:
      - "mysql"

volumes:
  dbdata:
